# Generated by Django 3.2.13 on 2022-04-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='favilogo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
