# Generated by Django 3.2.13 on 2022-04-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220414_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='bgimg',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
