# Generated by Django 3.2.13 on 2022-04-14 10:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_websiteinfo_bgimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='discription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
    ]
