# Generated by Django 3.2.13 on 2022-04-14 13:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[('Add To Home', 'Add To Home'), ('Normal', 'Normal')], default='Normal', max_length=255, null=True),
        ),
    ]
