# Generated by Django 3.2.13 on 2022-04-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='assets/img/testimonial/img1.png', null=True, upload_to='images'),
        ),
    ]
