# Generated by Django 3.2.13 on 2022-04-15 18:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title'),
        ),
    ]
