# Generated by Django 3.2.13 on 2022-04-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_addpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Medium', 'Medium'), ('Advance', 'Advance')], default='Free', max_length=255, null=True),
        ),
    ]
