# Generated by Django 3.2.13 on 2022-04-17 18:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_plan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='store_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
