# Generated by Django 3.2.13 on 2022-04-21 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0026_notification_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('make_com', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.DateTimeField(blank=True, null=True)),
                ('car_condition', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='POOR', max_length=255, null=True)),
                ('asking_price', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sold', models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Sold', 'Sold')], default='Buy', max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
