# Generated by Django 3.2.13 on 2022-04-21 08:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_seller_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='sno'),
        ),
    ]
