# Generated by Django 3.2.13 on 2022-04-21 09:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_seller_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='<django.db.models.fields.CharField>-<django.db.models.fields.CharField>-<django.db.models.fields.CharField> '),
        ),
    ]
