# Generated by Django 3.2.13 on 2022-04-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_seller_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
