# Generated by Django 3.2.13 on 2022-04-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_seller_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddPost',
        ),
    ]
