# Generated by Django 3.2.13 on 2022-04-22 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_delete_addpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.seller')),
            ],
        ),
    ]
