# Generated by Django 3.2.13 on 2022-04-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20220422_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amount',
        ),
    ]
